spring.application.name=backend
# 1. Đổi sang IP máy chủ của bạn (Hoặc giữ localhost nếu chỉ muốn backend kết nối nội bộ)
# URL kết nối đến MySQL Aiven chuẩn xác
spring.datasource.url=jdbc:mysql://mysql-2dcb00c6-duongvanminhtam30-22db.e.aivencloud.com:13626/phongkham_db2?useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true&serverTimezone=UTC

# Tài khoản đăng nhập
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_4qtJZDuZswtf35pZLaT

# Cấu hình Driver và Dialect cho MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Các cấu hình JPA bổ sung (giữ nguyên của bạn)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT Configuration
jwt.secret=VXNlclNlY3JldEtleUZvclBKU1Rva2VuU2lnbmluZ1RoaXMgSXMgVmVyeVNlY3VyZUtleUZvckJDUElOVFNlY3JldEtleUlOU05JSklOSU5JTkRISVNGSU5JU0hGSU5HU0hGSU5HU0hGSU5H
jwt.expiration=86400000

vnpay.tmn-code=1YNCE3P2
vnpay.hash-secret=0JGDU4BDI99U47EJWYPQ9ND4MLO6O31J
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html

# 2. BẮT BUỘC: Đổi localhost thành IP máy chủ để VNPay biết đường gọi về đúng máy xử lý dữ liệu
vnpay.return-url=https://qlpk-backend-spring-boot.onrender.com/api/payment/vnpay/return

# Backup Configuration (mysqldump / mysql)
backup.directory=./backups
backup.mysqldump-path=mysqldump
backup.mysql-path=mysql
